trying to create an alias to qa.mtp for qa deployment

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -62,18 +62,24 @@ jobs:
       url: ${{ steps.deploy.outputs.url }}
     steps:
       - uses: actions/checkout@v3
-
       - name: Install Vercel CLI
         run: npm install --global vercel@latest
-
       - name: Pull Vercel Environment Information
         run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
-
       - name: Deploy to QA
         id: deploy
         run: |
-          url=$(vercel deploy --token=${{ secrets.VERCEL_TOKEN }})
-          echo "::set-output name=url::$url"
+          vercel deploy --token=${{ secrets.VERCEL_TOKEN }} >deployment-url.txt 2>error.txt
+          code=$?
+          if [ $code -eq 0 ]; then
+            deploymentUrl=$(cat deployment-url.txt)
+            vercel alias $deploymentUrl qa.mtp.weekendwanderings.com --scope=your-team-or-username --token=${{ secrets.VERCEL_TOKEN }}
+            echo "::set-output name=url::qa.mtp.weekendwanderings.com"
+          else
+            errorMessage=$(cat error.txt)
+            echo "::error::Deployment failed: $errorMessage"
+            exit 1
+          fi
 
   prod-deploy:
       needs: [test, qa-deploy]
